version: "3.8"
services:
  db:
    container_name: gomin_db
    image: postgres:15.2
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: gomin
    ports:
      - "5435:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test -d gomin"]
      interval: 10s
      timeout: 5s
      retries: 5
  api:
    build:
      context: .
    container_name: gomin_api
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "1323:1323"
    restart: always
    environment:
      - APP_DB_USER=test
      - APP_DB_PASSWORD=test
      - APP_DB_HOST=gomin_db
      - APP_DB_PORT=5432
      - APP_DB_NAME=gomin
      - APP_PORT=1323